name: test

on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  Codecov-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: generate coverage
        run: |
          cd server
          go mod tidy
          go test ./... -race -covermode=atomic
